# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_gunnasutraLogin(object):
    def setupUi(self, gunnasutraLogin):
        gunnasutraLogin.setObjectName("gunnasutraLogin")
        gunnasutraLogin.resize(460, 175)
        self.gridLayoutWidget = QtWidgets.QWidget(parent=gunnasutraLogin)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 20, 441, 144))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.ok_cancel_button_box = QtWidgets.QDialogButtonBox(parent=self.gridLayoutWidget)
        self.ok_cancel_button_box.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.ok_cancel_button_box.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.ok_cancel_button_box.setCenterButtons(False)
        self.ok_cancel_button_box.setObjectName("ok_cancel_button_box")
        self.gridLayout.addWidget(self.ok_cancel_button_box, 5, 1, 1, 1)
        self.userIdLabel = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.userIdLabel.setObjectName("userIdLabel")
        self.gridLayout.addWidget(self.userIdLabel, 3, 0, 1, 1)
        self.userIdLineEdit = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.userIdLineEdit.setObjectName("userIdLineEdit")
        self.gridLayout.addWidget(self.userIdLineEdit, 3, 1, 1, 1)
        self.passphraseLineEntry = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.passphraseLineEntry.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.passphraseLineEntry.setObjectName("passphraseLineEntry")
        self.gridLayout.addWidget(self.passphraseLineEntry, 4, 1, 1, 1)
        self.passkeyLabel = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.passkeyLabel.setObjectName("passkeyLabel")
        self.gridLayout.addWidget(self.passkeyLabel, 4, 0, 1, 1)
        self.loginMessageLabel = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(18)
        self.loginMessageLabel.setFont(font)
        self.loginMessageLabel.setLineWidth(0)
        self.loginMessageLabel.setObjectName("loginMessageLabel")
        self.gridLayout.addWidget(self.loginMessageLabel, 0, 0, 1, 2)
        self.line = QtWidgets.QFrame(parent=self.gridLayoutWidget)
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 2, 0, 1, 2)

        self.retranslateUi(gunnasutraLogin)
        self.ok_cancel_button_box.accepted.connect(lambda: self.handle_ok()) # type: ignore
        # self.ok_cancel_button_box.rejected.connect(gunnasutraLogin.reject) # type: ignore
        self.ok_cancel_button_box.rejected.connect(lambda:self.handle_cancel()) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(gunnasutraLogin)

    def handle_ok(self):
        print ("OK! is pressed")
        gunnasutraLogin.accept() 

    def handle_cancel(self):
        print ("Cancel! is pressed")
        gunnasutraLogin.reject() 

    def retranslateUi(self, gunnasutraLogin):
        _translate = QtCore.QCoreApplication.translate
        gunnasutraLogin.setWindowTitle(_translate("gunnasutraLogin", "Gunnasutra Login"))
        self.userIdLabel.setText(_translate("gunnasutraLogin", "User ID"))
        self.userIdLineEdit.setPlaceholderText(_translate("gunnasutraLogin", "Enter User Id"))
        self.passphraseLineEntry.setPlaceholderText(_translate("gunnasutraLogin", "Enter Gunnasutra Passkey"))
        self.passkeyLabel.setText(_translate("gunnasutraLogin", "Passkey"))
        self.loginMessageLabel.setText(_translate("gunnasutraLogin", "Enter Gunnasutra Login Credentials"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    gunnasutraLogin = QtWidgets.QDialog()
    ui = Ui_gunnasutraLogin()
    ui.setupUi(gunnasutraLogin)
    gunnasutraLogin.show()
    sys.exit(app.exec())
